name: Build Mobywatel IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Resolve and Build
        run: |
          cd App
          
          # Generujemy projekt Xcode
          swift package generate-xcodeproj --xcconfig-overrides .xcodebuild.xcconfig || true
          
          echo "Dostępne schematy:"
          xcodebuild -list -project Mobywatel.xcodeproj

      - name: Archive
        run: |
          cd App
          
          xcodebuild clean archive \
            -project Mobywatel.xcodeproj \
            -scheme Mobywatel \
            -sdk iphoneos \
            -archivePath ../build/Mobywatel.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            -quiet

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath build/Mobywatel.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Mobywatel-IPA
          path: build/*.ipa
